In [1]:
import kagglehub
import pandas as pd
import os

# Baixa o dataset
path = kagglehub.dataset_download(
    "karkavelrajaj/amazon-sales-dataset"
)

print("Arquivos encontrados:")
print(os.listdir(path))

Using Colab cache for faster access to the 'amazon-sales-dataset' dataset.
Arquivos encontrados:
['amazon.csv']

In [2]:
import pandas as pd
import os

arquivo = os.path.join(path, "amazon.csv")

df = pd.read_csv(arquivo)

print("Linhas:", df.shape[0])
print("Colunas:", df.shape[1])

df.head()

Linhas: 1465
Colunas: 16

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [3]:
df[df["rating"].isnull()]

Empty DataFrame
Columns: [product_id, product_name, category, discounted_price, actual_price, discount_percentage, rating, rating_count, about_product, user_id, user_name, review_id, review_title, review_content, img_link, product_link]
Index: []

In [4]:
df["discounted_price"] = (
    df["discounted_price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["actual_price"] = (
    df["actual_price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["discounted_price"] = pd.to_numeric(
    df["discounted_price"],
    errors="coerce"
)

df["actual_price"] = pd.to_numeric(
    df["actual_price"],
    errors="coerce"
)

In [5]:
df["discount_percentage"] = (
    df["discount_percentage"]
    .str.replace("%", "", regex=False)
    .str.strip()
)

df["discount_percentage"] = pd.to_numeric(
    df["discount_percentage"],
    errors="coerce"
)

In [6]:
df["rating"] = pd.to_numeric(
    df["rating"],
    errors="coerce"
)

In [7]:
df["rating_count"] = (
    df["rating_count"]
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["rating_count"] = pd.to_numeric(
    df["rating_count"],
    errors="coerce"
)

In [8]:
df.isnull().sum().sort_values(ascending=False)

rating_count           2
rating                 1
product_id             0
product_name           0
discounted_price       0
category               0
discount_percentage    0
actual_price           0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [9]:
print("Preço com desconto:")
print(df["discounted_price"].describe())

print("\nPreço original:")
print(df["actual_price"].describe())

print("\nDesconto:")
print(df["discount_percentage"].describe())

print("\nRating:")
print(df["rating"].describe())

print("\nQuantidade de avaliações:")
print(df["rating_count"].describe())

Preço com desconto:
count     1465.000000
mean      3125.310874
std       6944.304394
min         39.000000
25%        325.000000
50%        799.000000
75%       1999.000000
max      77990.000000
Name: discounted_price, dtype: float64

Preço original:
count      1465.000000
mean       5444.990635
std       10874.826864
min          39.000000
25%         800.000000
50%        1650.000000
75%        4295.000000
max      139900.000000
Name: actual_price, dtype: float64

Desconto:
count    1465.000000
mean       47.691468
std        21.635905
min         0.000000
25%        32.000000
50%        50.000000
75%        63.000000
max        94.000000
Name: discount_percentage, dtype: float64

Rating:
count    1464.000000
mean        4.096585
std         0.291674
min         2.000000
25%         4.000000
50%         4.100000
75%         4.300000
max         5.000000
Name: rating, dtype: float64

Quantidade de avaliações:
count      1463.000000
mean      18295.541353
std       42753.864952
min           2.000000
25%        1186.000000
50%        5179.000000
75%       17336.500000
max      426973.000000
Name: rating_count, dtype: float64

In [10]:
categorias_df = df["category"].str.split("|", expand=True)
categorias_df.columns = [f"categoria_{i+1}" for i in range(categorias_df.shape[1])]
df = pd.concat([df, categorias_df], axis=1)

df["rating_count"] = df["rating_count"].fillna(0)

df["discount_amount"] = df["actual_price"] - df["discounted_price"]

df = df.drop_duplicates(subset=["product_id"]).reset_index(drop=True)
df.to_csv("amazon_sales_cleaned.csv", index=False)
print(f"Arquivo 'amazon_sales_cleaned.csv' gerado com sucesso! Total de linhas únicas: {len(df)}")

Arquivo 'amazon_sales_cleaned.csv' gerado com sucesso! Total de linhas únicas: 1351

In [11]:
print("Linhas:", len(df))
print("Produtos únicos:", df["product_id"].nunique())
print("Linhas completamente duplicadas:", df.duplicated().sum())

Linhas: 1351
Produtos únicos: 1351
Linhas completamente duplicadas: 0

In [12]:
duplicados_produto = (
    df[df["product_id"].duplicated(keep=False)]
    .sort_values("product_id")
)

print("Linhas envolvidas:", len(duplicados_produto))
print("Produtos duplicados:", duplicados_produto["product_id"].nunique())

duplicados_produto[
    ["product_id", "product_name", "rating_count",
     "discounted_price", "actual_price", "discount_percentage"]
]

Linhas envolvidas: 0
Produtos duplicados: 0

Empty DataFrame
Columns: [product_id, product_name, rating_count, discounted_price, actual_price, discount_percentage]
Index: []